name: Changed files

on:
  push:
    branches:
      - main

permissions:
  actions: read
  attestations: write
  checks: read
  contents: write
  deployments: write
  pull-requests: write
  repository-projects: write
  statuses: write

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v44
        with:
          files: docs/**
          files_ignore: docs/static.md

      - name: Run step if any file(s) in the docs folder change
        id: changed-files
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: ${{ env.ALL_CHANGED_FILES }}"
          
      - name: append file
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: "DamianReeves/write-file-action@master"
        with:
          path: docs/static.md
          write-mode: append
          contents: |
            ${{ steps.changed-files-specific.outputs.all_changed_files }}
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'appended by Github Actions - ${date}'
