name: Repo - Actions parameter in README
# description: Renders Markdown tables for inputs and outputs from actions.yml file.
# description: https://github.com/mdvorak/update-action-readme

#<!--(inputs-start)-->
#<!--(inputs-end)-->

#<!--(outputs-start)-->
#<!--(outputs-end)-->

run-name: render actions.yml Inputs/Outputs for README tables by ${{ github.actor }}

on:
  push:
    branches: ["main"]
    paths:
      - action.yml
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"
          fetch-depth: 0

      - name: Update README.md
        uses: mdvorak/update-action-readme@v1
        with:
          file: "./README.md"
          action-file: "./action.yml"

        # https://github.com/ad-m/github-push-action
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'appended by Github Actions - ${date}'
